version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/testing
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306" # Map external port 3307 to container's internal port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
      MYSQL_DATABASE: testing  # Initialize a database
